### ISSUE TITLE
Poprawa dokumentacji

### ISSUE THREAD

**Issue by mmiklas** [Kalina7911/Travel-Allowance-Project#1]
- można popracować nad formatowaniem (nagłówki i wypunktowanie w markdown),
- opisy w dokumentacji odbiegają od tego co widzę w projekcie (poprawić projekt lub dokumentację), np. widok 1 - opisy są tylko w wersji angielskiej, widok 2 - jak uzupełnić Preferences, co to jest index itp.,
- konieczny opis jak tego używać, bo trudno (przynajmniej mi) to zrozumieć (czy w preferences podajemy pojedyncze dni? dokumentacja opisuje coś innego itp.)

**Comment by Kalina7911** [comment]
Dokumentacja poprawiona. Dodałam opis krok po kroku , jak wprowadzać dane na stronie Preferences i jak wyświetlać dane na stronie Rate of Allowance

**Comment by Kalina7911** [comment]
Chciałam jeszcze upewnić sie ,że mówimy o tym samym projekcie. Projekt, który jest przygotowany do zaliczenia w moim repozytorium znajduje się pod tytułem travel-allowance. Pierwotnie zgłaszałam repozytorium Travel-Allowance-Project. Informowałam Pana o tej zmianie w korenspondencji na szusi i zaakceptowała ją Pan. Link do projektu na zaliczenie : https://github.com/Kalina7911/travel-allowance

**Comment by mmiklas** [comment]
Tak - teraz widzę, że powinieniem to zgłosić w innym miejscu - zamykam.
